import test_location
import test_new_demo
import test_adt
import test_operations
import test_devices
import test_api
import test_user_management
import test_api_demo
import test_activity_extension
import test_auditing
# import test_activity_access
