from . import test_adt_patient_register
from . import test_adt_patient_update
from . import test_adt_patient_admit
from . import test_adt_patient_cancel_admit
from . import test_adt_patient_discharge
from . import test_adt_patient_cancel_discharge
from . import test_adt_patient_transfer
from . import test_adt_patient_cancel_transfer
from . import test_adt_spell_update
from . import test_adt_patient_merge
