from . import test_api_register
from . import test_api_update
from . import test_api_admit
from . import test_api_admit_update
from . import test_api_cancel_admit
from . import test_api_discharge
from . import test_api_cancel_discharge
from . import test_api_merge
from . import test_api_transfer
from . import test_api_cancel_transfer
