# -*- encoding: utf-8 -*-
{
    'name': 'NH Base',
    'version': '0.1',
    'category': 'Base',
    'license': 'AGPL-3',
    'summary': 'NH Base',
    'description': """ NH Base   """,
    'author': 'Neova Health',
    'website': 'http://www.neovahealth.co.uk/',
    'depends': [],
    'data': [],
    'demo': [],
    'images': [],
    'css': [],
    'test': [],
    'application': True,
    'installable': True,
    'active': False,
} 
